AWSTemplateFormatVersion: "2010-09-09"
Description: AI Resume Website Infrastructure (S3 + DynamoDB)

Parameters:
  BucketName:
    Type: String
    Default: ai-resume-brr

Resources:

  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ResumeBucket.Arn}/*"

  DeploymentTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DeploymentTracking
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deployment_id
          AttributeType: S
      KeySchema:
        - AttributeName: deployment_id
          KeyType: HASH

  ResumeAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResumeAnalytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: resume_id
          AttributeType: S
      KeySchema:
        - AttributeName: resume_id
          KeyType: HASH

Output
